# Flows

## Install prerequisites

In [1]:
# !cd .. && make install
# !pwd

In [2]:
import sys
from pprint import pprint
from dotenv import load_dotenv, find_dotenv

sys.path.append('..')

load_dotenv(find_dotenv())

%load_ext autoreload
%autoreload 2

In [17]:
import asyncio
import nest_asyncio
nest_asyncio.apply()

In [28]:
# Disable cache for testing
import os
os.environ['PROVIDER_CACHE_ENABLED'] = 'False'  
os.environ['FLOW_CACHE_ENABLED'] = 'False'

## Markets

In [26]:
from datetime import datetime

base_date = datetime(2023, 1, 1)

### BuffetIndicatorWorkflow

In [29]:
from app.flows.markets import fetch_buffet_indicator_data

asyncio.run(fetch_buffet_indicator_data(base_date=base_date))['data']

Empty DataFrame
Columns: []
Index: []

## Portfolio

## Screen

## Compare

In [30]:
from datetime import datetime

base_date = datetime(2023, 1, 1)
tickers=["AAPL", "MSFT", "GOOGL"]

### fetch_returns_data

In [31]:
from app.flows.compare import fetch_returns_data

asyncio.run(fetch_returns_data(tickers=tickers, base_date=base_date))['data']

                                AAPL        MSFT       GOOGL
Date
2023-01-03 00:00:00-05:00   0.000000    0.000000    0.000000
2023-01-04 00:00:00-05:00   1.029758   -4.373749   -1.173947
2023-01-05 00:00:00-05:00  -0.040542   -7.210085   -3.273507
2023-01-06 00:00:00-05:00   3.640639   -6.115583   -1.997968
2023-01-09 00:00:00-05:00   4.062272   -5.199949   -1.230387
...                              ...         ...         ...
2025-08-11 00:00:00-04:00  84.204979  122.209446  126.887911
2025-08-12 00:00:00-04:00  86.207735  125.390741  129.529292
2025-08-13 00:00:00-04:00  89.191600  121.702653  127.971554
2025-08-14 00:00:00-04:00  88.745642  122.511818  129.077774
2025-08-15 00:00:00-04:00  87.780751  121.528044  130.161418

[657 rows x 3 columns]

### fetch_rsi_data

In [32]:
from app.flows.compare import fetch_rsi_data

asyncio.run(fetch_rsi_data(tickers=tickers, base_date=base_date))['data']

                                AAPL       MSFT      GOOGL
Date
2023-01-03 00:00:00-05:00  22.619388  35.426731  39.893100
2023-01-04 00:00:00-05:00  23.277573  22.420073  30.554117
2023-01-05 00:00:00-05:00  23.894063  19.325923  28.626880
2023-01-06 00:00:00-05:00  39.498141  26.540755  40.034169
2023-01-09 00:00:00-05:00  43.028534  32.144338  43.707483
...                              ...        ...        ...
2025-08-11 00:00:00-04:00  65.390071  62.160967  66.395112
2025-08-12 00:00:00-04:00  67.677448  65.640477  71.358749
2025-08-13 00:00:00-04:00  70.717423  56.189382  66.246266
2025-08-14 00:00:00-04:00  69.838308  55.663180  66.212625
2025-08-15 00:00:00-04:00  68.047097  54.883484  68.581747

[657 rows x 3 columns]

### fetch_volatility_data

In [33]:
from app.flows.compare import fetch_volatility_data

asyncio.run(fetch_volatility_data(tickers=tickers, base_date=base_date))['data']

                                AAPL       MSFT      GOOGL
Date
2023-01-03 00:00:00-05:00  32.708782  29.717506  31.746987
2023-01-04 00:00:00-05:00  32.930390  32.296689  31.794432
2023-01-05 00:00:00-05:00  32.618859  33.265616  31.906936
2023-01-06 00:00:00-05:00  34.388400  33.245926  31.813354
2023-01-09 00:00:00-05:00  34.342411  33.224045  31.545868
...                              ...        ...        ...
2025-08-11 00:00:00-04:00  25.915582  17.671520  20.065703
2025-08-12 00:00:00-04:00  25.545865  18.041561  19.520278
2025-08-13 00:00:00-04:00  25.657602  18.456803  19.708262
2025-08-14 00:00:00-04:00  25.124380  18.425418  19.419553
2025-08-15 00:00:00-04:00  25.230672  18.051494  19.418958

[657 rows x 3 columns]

### fetch_volume_data

In [34]:
from app.flows.compare import fetch_volume_data

asyncio.run(fetch_volume_data(tickers=tickers, base_date=base_date))['data']

                                AAPL      MSFT     GOOGL
Date
2023-01-03 00:00:00-05:00  112117500  25740000  28131200
2023-01-04 00:00:00-05:00   89113600  50623400  34854800
2023-01-05 00:00:00-05:00   80962700  39585600  27194400
2023-01-06 00:00:00-05:00   87754700  43613600  41381500
2023-01-09 00:00:00-05:00   70790800  27369800  29003900
...                              ...       ...       ...
2025-08-11 00:00:00-04:00   61806100  20194400  25832400
2025-08-12 00:00:00-04:00   55626200  18667000  30397900
2025-08-13 00:00:00-04:00   69878500  19619200  28342900
2025-08-14 00:00:00-04:00   51916300  20269100  25230400
2025-08-15 00:00:00-04:00   56010500  25191800  34911300

[657 rows x 3 columns]

## Optimize

## Backtest